version: "3.3"

services:
    mysql:
        image: mysql:5.7
        volumes: 
            - payment-mysql-data:/var/lib/mysql
            - ./scripts:/docker-entrypoint-initdb.d
        environment: 
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mfv
    app:
        build: .
        image: payment-service
        ports:
            - 8080:8080
        depends_on: 
            - mysql

volumes: 
    payment-mysql-data: